Prepare valid travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,11 +23,11 @@ before_script:
   
   - > 
     if  [ -d ./test_fields ] && ! [ `ls ./test_fields | wc -l` -eq 0 ] ; then 
-        echo "Preparing user fields..."
-	sudo cp -r ./test_fields/. $volume_path/custom_fields
+      echo "Preparing user fields..."
+      sudo cp -r ./test_fields/. $volume_path/custom_fields
     else
-	echo "Fields not found in ./test_fields !!!"
-	exit 1
+      echo "Fields not found in ./test_fields !!!"
+      exit 1
     fi
   
 script:
